export const LinkAccount = [
    "current_owner",
    "voter",
    "open_owner",
    "producer",
    "publisher",
    "creator",
    "from",
    "to",
    "opCurator",
    "author",
    "benefactor",
    "comment_author",
    "parent_author",
  ];

  export const StringFieldArray = [
    "id",
    "weight",
    "rshares",
    "total_vote_weight",
    "account",
    "json_meta",
    "memo",
    "author_rewards",
    "open_orderid",
    "current_orderid",
    "fill_or_kill",
    "expiration",
    "orderid",
    "json_metadata",
    "body",
    "title",
    "allow_votes",
    "percent_hbd",
    "allow_curation_rewards"

  ];

  export const ObjectFieldArray = [
    "vesting_shares",
    "reward",
    "amount",
    "reward_hive",
    "hbd_payout",
    "fee",
    "pending_payout",
    "reward_hbd",
    "reward_vests",
    "hive_payout",
    "vesting_payout",
    "total_payout_value",
    "curator_payout_value",
    "beneficiary_payout_value",
    "curators_vesting_payout",
    "initial_vesting_shares",
    "initial_delegation",
    "amount_back",
    "current_pays",
    "open_pays",
    "min_to_receive",
    "amount_to_sell",
    "max_accepted_payout"
  ];