export default {
    HOME: `/`,
    ABOUT:'/about',
    Contact:'/contact',
    Service:'/service',
    HeadBlock:'/head/b/:id',
    TargetBlock:'/b/:id',
    Transactions:'/transactions',
    TargetTransaction:'/tx/:id',
    User:'/@:user_id',
    UserTransaction:'/@:user_id/transactions',
    UserAuthorities:'/@:user_id/authorities',
    Blocks:'/blocks',
    Witnesses:'/witnesses',
    Proposals:"/proposals",
    SingleProposal:"/proposals/:id",
    Entry:"/@:user_id/:permlink",
    EntryComment:"/:category/@:user_id/:permlink",
    APIDocumentation:"/api-docs"
};
